#include "Tensor.h"
#include "tensor_defines.h"
#include "../_autograd/operations.h"

namespace statkitcpp {

TENSOR_BINARY_DECLARATIONS_WITH_OP(OPERATOR_METHODS_DEFINITIONS)

// TENSOR_BINARY_DECLARATIONS_WITH_OP(OPERATORS_DEFINITIONS)

TENSOR_BINARY_DECLARATIONS_WITHOUT_OP(OPERATOR_METHODS_DEFINITIONS)

TENSOR_LINALG_OPERATIONS_WITH_OP(LINALG_METHODS_DEFINITIONS)
TENSOR_LINALG_OPERATIONS_WITHOUT_OP(LINALG_METHODS_DEFINITIONS)

TENSOR_AGGREGATION_METHODS(AGGREGATION_DEFINITIONS)

TENSOR_POINTWISE_METHODS(POINTWISE_DEFINITIONS)

}
